### PR TITLE
Check for the config file on the pdo connection

### PR DESCRIPTION
**Pull request by xh3n1**

### CODE REVIEW

**Comment by samtuke** [comment]
Are you sure that $_SERVER['ConfigFile']; is always an absolute URL? How about printing the file path in the exception message to make it easier for admins to debug?

**Comment by samtuke** [comment]
@xh3n1?

**Comment by xh3n1** [comment]
@samtuke good question. I'm checking.

**Comment by xh3n1** [comment]
@samtuke Based on the following manual and other places where ConfigFile variable is used, I think it should be an absolute path. Anyway, the config file is only needed to set the maintenance mode on/off and I will update the message to make it easier to debug.

 https://resources.phplist.com/develop/developmentsetup?fbclid=IwAR2d0i4NfkBaxlZDJQYYzay83ysgPSMeULupJjPXbaYLQqbBQAs92dK_76I

**Comment by samtuke** [comment]
@xh3n1 OK thanks. I'll wait for that before merging.

**Comment by samtuke** [comment]
@xh3n1 In order to get out the new RC I'll merge this now

**Pull request merged**
